#!/bin/bash

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  echo "Downloading plugin manager (Plug). This may take a while ☕️"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

cp ./.vimrcplugins ~/.vimrc
cp ./.vimrcplugins ~/.vimrcplugins

vim +PlugInstall +qa

if [ ! -d ~/.oh-my-zsh ]; then
  echo "Downloading Oh My ZSH ☕️"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

echo "Copying dotfiles"
cp ./.bash_profile ~/bash_profile
cp ./.zshrc ~/.zshrc
cp ./.vimrc ~/.vimrc
cp ./.gitignore_global ~/.gitignore_global
node replacer.js ./.gitconfig > ~/.gitconfig

source ~/.zshrc

echo "All done 🍺"

